version: '3.3'
services:
  app:
    image: $REGISTRY/$REPOSITORY:${BUILD_TAG}
    container_name: hellobot
    restart: always
    volumes:
      - data:/data
    environment:
      - BOT_TOKEN
      - PERSIST_PATH
      - BOT_ADMINS_0
      - BOT_ADMINS_1

volumes:
  data:
